#+title: 比特币的概念学习

** 参考资料

1. [[https://www.zhihu.com/question/22076666][比特币基础科普与常见误解]]
2. [[https://www.zhihu.com/question/20941124][比特币系统是如何动作的]]


** 个人的一些随记

- 从运行上来看，比特币实际上是一个互联网上的去中心化账本。
- 所谓的智能合约是一套以编程形式定义的合同 ，无需人为介入即可自动执行。
  智能合约能操纵真实世界的资产，当一个预先编好的条件被触发时，智能合约执行相应的合同条款，
  以此实现“可编程的经济”，例如去中心化的股票、保险、赌博等等功能，
  并在物联网、供应链等领域得到广泛应用。可编程的经济将能显著解决经济运行中的透明和可信问题，降低社会运行成本。
- 注：大部分智能合约，均需要在比特币目前系统基础上叠加附加规则或侧链，以此实现相应功能。
  目前以有部分比特币侧链、竞争币实现了实验性的各种智能合约系统。如果某些智能合约系统被市场证明有价值，
  那也可通过附加规则或侧链方式用于比特币系统上。

**** 什么是比特币挖矿

   去中心化账本（比特币）” 中所述，比特币节点互相连接时，会从对方处获取自己没有的交易。
   但由于比特币长期积累天量的交易，两个节点逐条对照你缺了哪些交易/我缺了哪些交易，是非常困难的事情。

   为解决这一难题，中本聪发明了区块链（Block chain）这一重要技术。节点借助区块（block）来同步交易，
   保证了所有节点数据的统一性，并通过竞争区块打包权（也就是挖矿）的方式，保证了区块链的唯一性。

1. 区块和区块键
   一段时间内的交易打成的一个包称为区块，比特币全网平均每10分钟产生一个区块，每一个区块都链接到上一个区块，依次相连形成区块链。
2. 以匹块为单位同步交易数据
   区块从1开始编号，因此节点A连接节点B后，只要检查双方的区块编号高度，就能方便地同步交易数据。
   例如节点A自己的区块高度是100，发现节点B的区块高度是110，则只要向B请求同步101~110这10个区块即可。
3. 打包区块的奖励
   为保证有节点打包比特币交易，比特币规则规定：打包交易的节点将获得比特币作为酬劳。

   - 打包奖励的一部分来自交易创建者支付的交易手续费（每KB交易大小100~1000聪手续费）。
   - 另一部分来自初始2100万个比特币的分发，最开始奖励是每个区块50比特币，之后每经过21万个区块（约4年时间）奖励将减半一次，
      直到2140年左右区块奖励不足1聪为止，此时区块奖励总和为2100万比特币，
      这就是比特币2100万总量的来源（准确地说是20999999.97690000个）。2140年后打包奖励将只来自于交易创建者支付的交易手续费。

4. 对区块打包权的竞争
		节点打包交易只需要消耗很低成本的网络和计算资源，打包奖励的存在（目前每个区块的打包奖励25比特币约为4万元），
		使得有大量节点想打包交易。为保证区块链的唯一性，
		比特币规则规定：节点使用类似“扔硬币”的方法争夺交易打包权。
		节点不断地扔硬币，谁首先扔出符合规则的结果，谁就能获得这个区块的交易打包权，以及这个区块的打包奖励。
		
5. 竞争交易打包权的方式
		“扔硬币”在实现上是计算机做一次哈希（SHA-256）运算，
		并检查运算结果从第一位开始是否有足够多连续的0（可以简单理解为一次扔256个硬币，然后看从第一个硬币开始是否有足够多的连续硬币正面）。
		“扔硬币”获胜的唯一诀窍是提高每秒扔硬币的次数，一个每秒能扔100亿次硬币（做100亿次哈希计算）的节点，
		抢到打包权的概率是每秒扔1亿次硬币节点的100倍。	
		
6. 获胜节点打包交易并广播
		一旦有某个节点扔出符合系统规则的硬币结果（例如区块379543的哈希值 000000000000000008bdeb575056584429ea4be876ea7ca4ce70262d3edb8c8b），
		他就会立即将这段时间搜集到的交易打包成一个区块，附上“扔硬币”的结果、区块序号379543、上一区块关系等附加信息广播出去，
		其它节点一旦收到区块379543并验证无误，就会停止“扔硬币”抢这一区块，转而在这一区块的基础上开始“扔硬币”抢下一区块379544。		
		
7. “挖矿”和“矿工”的由来
		节点大量进行哈希计算需要计算机设备，并消耗大量电力，这个过程在本质上和金矿挖矿很相似（通过挖矿设备，消耗能源换取黄金）。
		比特币总量恒定，产量越来越少的产生方式也和黄金很相似。
		因此人们形象地将比特币抢打包权的过程称为挖矿（mine），将抢打包权的比特币节点称为矿工（miner）。		
		
**** 矿池
		由于有数以万计的矿工竞争打包权，单个矿工抢得打包权的概率非常小，产出非常不稳定，
		有可能走狗屎运1小时就抢到一次，也有可能一年都抢不到一次。为稳定挖矿产出，矿工往往选择加入矿池挖矿，
		矿池将大量矿工的算力整合在一起，在全网总算力中占据一定的份额，由此得到较稳定的挖矿产出，矿池在收取2%~4%矿池手续费后，
		将产出按矿工算力分配给矿工。这就好比一个人买彩票很难中奖，于是矿池把很多人组织在一起买彩票，
		中奖了再按出资额分配给大家。随着矿池的发展，还出现了像莱比特这样的自动切换矿池，俗称机枪池。
		机枪池会在各种山寨币收益高时切换到山寨币挖矿，以此将矿工的收入提高5%~10%。	
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		





















