#+title: 色达

**** 路线

成都自驾去色达线路1：成都（高速，60km）——映秀（G317，260km）——马尔康（G317，200km）——翁达村（V18县道，63km）——色达喇荣五明佛学院
线路状况：全程580km，用时至少需要12小时，成都——映秀的高速比较好走，下了高速就有可能遇到堵车，国道路不好，车也多，所以行驶速度不会快。而且汶川——马尔康的路况还好，车也不多，风景也不错可以好好享受。马尔康——色达的路况不好，特别是从翁达村下国道之后路况非常差。


成都自驾去色达线路2：成都（成雅高速，130km）——雅安（318国道，194km）——康定（318国道，75.8km）——新都桥（215省道，213km）——炉霍（317国道，72km）——翁达镇（V18县道，63km）——色达喇荣五明佛学院
线路状况：全程742km，全程开车至少需要16小时，成都到雅安是高速，非常快捷；出雅安之后就上了318国道，一直到泸定路上卡车会比较多，路比较窄，容易堵车，经康定抵达新都桥，这一段路的风景都非常好，可以考虑在康定或者新都桥住一晚。新都桥——炉霍是215省道，将经过塔公草原，路况不好，但一路都是风景，可以边走边玩。炉霍到色达的路况不好，特别是从翁达村下国道之后路况非常差。


摘要：从2015年6月25日至2015年9月30日，色达歌乐沱乡（K38+200）至炉霍县新都镇(K133+900)路段进行交通管制。成都前往色达自驾线路推荐： 1、成都--理县--阿坝--久治--班玛--色达线路。全程约850KM，路况良好，家轿可顺利通过 2、成都--马尔康--观音桥--黑桥--壤塘--色达线路。全程约680KM。国道317观音桥K420+000至G317黑桥段（约80KM路程）公路改建施工，此路段路况较差，车辆缓行。到达黑桥后进入阿两路前往壤塘，经年龙至色达。



1、初入高原，不可暴饮暴食，以免加重消化器官的负担，不要饮酒和吸烟，不能剧烈运动，使其能很好地适应此环境，要防止因受凉而引起的感冒。
2、要多食蔬菜，水果等富含维他命的物质，要多饮水。
3、严格来说，色达是不允许拍摄的。山底有个检查站，上山的除了喇嘛和工作人员，其余人都要身份证登记，并且扣押相机包。
4、色达全县平均海拔4127米，属于高海拔地区，很多人在这里都会出现不同程度的高反症状，即使没有高反症状在这边活动也会或多或少会觉得吃力，初到高原不要多做剧烈运动，第一天到尽量不要洗澡，可以提前吃些红景天等预防高反，可以吃些高糖的食品，喝得惯的话也可以多喝些酥油茶，对抵抗高反也有较好的效果。高原反应没什么可怕的，大多数人好好休息一下就会逐渐适应了。
5、色达海拔高，早晚温差大，平均温度低，去色达旅游，即使在最热的季节，也要带上足够的防寒衣物。秋、冬、春季请带羽绒服或其他厚衣服，即使夏季一件外套也不足够御寒；另外佛学院的住宿处没有暖气，需要注意做好保暖措施。因温差大的关系，初到这里的人很容易引起感冒，最好提前准备好感冒药。


